identifier: arckeys
name: Arckeys
type: keyboard
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - adc
  - gpio
  - usb_device
  - kscan
  - ble
  - ieee802154
  - pwm
  - watchdog